export type feedDetailsType = {
  id: number;
  title: string;
  description: string;
  detail: string;
  start_date: string;
  end_date: string;
  approved: string;
  user_id: number;
  view_count: number;
  click_count: number;
  created_at: string;
  updated_at: string;
  organization_id: number;
  organization_name: string;
  organization_logo: string;
  avatar: string;
  promotion_url: string;
  share_count: number;
  status: boolean;
  like: boolean;
  promotion_category: string;
  saved: boolean;
  avatar_content_type: any;
};
